config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  #
  root to: 'lists#index'

  resources :lists do
    resources :bookmarks, only: [ :new, :create ]
  end

  resources :bookmarks, only: [ :destroy ]

  # resources :movies, only: [ :index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  #foundation for form
  def new
    @bookmark = Bookmark.new(list_id: params[:list_id])
    @movies = Movie.all
    @list = List.find(params[:list_id])
  end

  # params for the form
  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      @movies = Movie.all
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private
  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :list_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @movies = Movie.all
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @movies = @list.movies
    @bookmarks = @list.bookmarks.includes(:movie)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
  end

  def destroy
      @list = List.find(params[:id])
      if @list.destroy
        redirect_to lists_path, status: :see_other, notice: 'List deleted!'
      else
        redirect_to lists_path, status: :unprocessable_entity, alert: 'Could not delete'
      end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/new.html.erb
<h1>Add a movie to <%= @list.name %></h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :movie_id, collection: @movies, label: "Select a movie", prompt: "Choose a movie" %>
  <%= f.input :comment %>
  <%= f.hidden_field :list_id, value: @list.id %>
  <%= f.submit "Add to list" %>
<% end %>
<%= link_to "Back to movie", list_path(@list) %>
<%# you can use association instead of collection %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/index.html.erb
<%# NAVBAR %>
<%# BANNER %>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/1040160/pexels-photo-1040160.jpeg);">
  <div class="container">
    <h1>Plan your next chill sesh</h1>
    <p>Save and share your favorite movies</p>
    <a href="#"><%= link_to "Start Here", new_list_path, class: "btn btn-warning text-dark" %></a>
  </div>
</div>
<%# Heading %>
<div class="container">
  <div class="no-lists-warning">
    <% if @lists.none? %>
      <p><%= "No lists yet!" %></p>
    <% end %>
  </div>
</div>
<%# CARDS %>
<div class="container">
  <div class="cards">
    <% @lists.each do |list| %>
      <%= link_to list_path(list), class: "text-dark text-decoration-none" do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url( <%= list.photo.attached? ? cl_image_path(list.photo.key) : 'https://ducunl0s4svtl.cloudfront.net/wp-content/uploads/2017/10/flat-clapperboard-icon_1063-38.jpg' %>)">
          <%= list.name %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<h1>Add a New List</h1>
<p>Your binge starts here</p>
<%= simple_form_for @list do |f| %>
  <%= f.input :name%>
  <%= f.input :photo, as: :file %>
  <%= f.submit%>
<% end %>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @list.photo.attached? ? cl_image_path(@list.photo.key) : 'https://ducunl0s4svtl.cloudfront.net/wp-content/uploads/2017/10/flat-clapperboard-icon_1063-38.jpg' %>)">
  <div class="container">
    <h2 class="banner-text"><%= @list.name%></h2>
  </div>
</div>
<% @bookmarks.each do |bookmark| %>
  <p><%= bookmark.movie.title %>: <%= bookmark.comment %></p>
  <div>
    <%= link_to bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-warning" do %>
      <p>Delete this bookmark</p>
    <% end %>
  </div>
<% end %>
<%# -------- %>
<%# -------- %>
<%= link_to "Go back",  lists_path, class: "btn btn-primary" %>
<%= link_to "Add a movie to this list (bookmark)", new_list_bookmark_path(@list), class: "btn btn-secondary" %>
<div>
  <%= link_to list_path(@list.id), data: { turbo_method: :delete, turbo_confirm: "Do you want to delete #{@list.name}?" } do %>
    <p>Delete this list</p>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img class="navbar-home-button" src="https://images.pexels.com/photos/5662857/pexels-photo-5662857.png" />
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <a> <%= link_to "Home", lists_path, class: "nav-link" %> </a>
        </li>
        <li class="nav-item">
          <a> <%= link_to "New List", new_list_path, class: "nav-link" %> </a>
        </li>
        <li class="nav-item dropdown">
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" data-turbo-method="delete" href="#">Log out</a>
          </div>
        </li>
        <!--li class="nav-item"-->
        <!--/li-->
      </ul>
    </div>
  </div>
</div>